apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: openshift-cudn-bgp-routing-metrics-reader-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-cudn-bgp-routing-metrics-reader
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
